name: awesome_app

services:
  nginx:
    container_name: awesome_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOSTNAME: ${HOSTNAME}
    ports:
      - ${PORT}:80
      - ${SSL_PORT}:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - awesome_app
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:6.7.2-php8.3-fpm-alpine
    container_name: awesome_wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${DATABASE_HOST_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
    volumes:
      - wordpress:/var/www/html
      - ../:/var/www/html/wp-content/plugins/awesome
      - ./wp-config.php:/var/www/html/wp-config.php
    depends_on:
      database:
        condition: service_healthy
    networks:
      - awesome_app
    healthcheck:
      test: curl -f http://localhost/license.txt
      interval: 5s
      timeout: 30s
      retries: 5

  database:
    image: mysql:8.4
    container_name: ${DATABASE_HOST_NAME}
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 5s
      timeout: 60s
      retries: 5
    volumes:
      - database:/var/lib/mysql
    networks:
      - awesome_app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: awesome_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${DATABASE_HOST_NAME}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${PMA_PORT}:80
    volumes:
      - phpmyadmin:/var/lib/phpmyadmin
    depends_on:
      database:
        condition: service_healthy
    networks:
      - awesome_app

volumes:
  wordpress:
  database:
  phpmyadmin:

networks:
  awesome_app:
    driver: bridge
